const COLORS = {
  ACCENT: '#bf66ff',
  DARKER_ACCENT: '#3b0066',
  BLACK: 'black',
  WHITE: 'white',
  GREY: '#e6e6e6',
};

const BOTTOM_BORDER_WIDTH_SELECTED = 8;
const BOTTOM_BORDER_WIDTH_DEFAULT = 4;

export { COLORS, BOTTOM_BORDER_WIDTH_SELECTED, BOTTOM_BORDER_WIDTH_DEFAULT };
