const COLORS = {
  BASE: '#534483',
  ACCENT: '#34275E',
  DARK: '#150E2D',
  LIGHT: '#796AAB',
  LIGHTER: '#BAB2D5',
  WHITE: 'white',
};

const DEFAULT_BORDER_WIDTH = 5;

export { COLORS, DEFAULT_BORDER_WIDTH };
